project:
  type: website


website:
  title: "Intrinsic order"
  navbar:
    background: primary
    search: True
    left:
      - text: "Home"
        file: index.qmd
      - text: "Generative AI"
        file: generative_ml/index.qmd

  sidebar:
    - title: "Home"
      stlye: "floating"
      contents:
        - index.qmd
        - about.qmd

    - title: "What is a generative model?"
      contents: 
        - generative_ml/index.qmd
        - generative_ml/vae_1.md
    
       


  # page-footer:
  #   right: "This page is built with [Quarto](https://quarto.org/)."
  #   left: "something else"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 2
    page-layout: article
    


